### ISSUE TITLE
Use DataSync for moving world data between S3 and EFS

### ISSUE THREAD

**Issue by briancaffey** [gotodeploy/cdk-valheim#70]
Thanks for providing this great construct! I have used it recently to setup a dedicated server and it is working well. Would it make sense to add DataSync tasks to sync data between EFS and an S3 bucket where world data can be uploaded? How would you recommend moving world data stored on local machine to EFS?

**Comment by gotodeploy** [comment]
@briancaffey Thank you for using this construct :bow: To be honest, I didn't know AWS DataSync till I see this issue. It's not a recommend way but I used AWS Transfer and scp to sync world data between local storage and EFS. I'm confirming how DataSync works. Let me know if you are willing to send a PR by the way.

**Comment by briancaffey** [comment]
@gotodeploy Ah OK, I did look into AWS Transfer Family initially but I didn't like the idea that you had to start a server in order to transfer files. I think that DataSync should be simpler based on my experience with it so far. 

I have successfully moved data from EFS to S3 using the L1 DataSync constructs. I did have to hard-code some ARNs to make the permissions work correctly. I am working out of a private GitLab repo for the moment but I'll get it mirrored to GitHub soon so I can share that with you. Next I need to set up the DataSync Task for moving data from S3 into EFS at the correct location. I'm not sure it needs to be part of this construct, but I would be happy to share with you how I think it could be.

**Comment by gotodeploy** [comment]
> I didn't like the idea that you had to start a server in order to transfer files.

Same here, and I feel that pricey( :money_with_wings: $0.30 per hour ).

Nice to hear about your success. I'm looking forward to it getting mirrored to GitHub :bow: I believe world data syncing is one of the basic operations and it should be a part of this construct. Sadly there is no L2 DataSync construct at the moment so I think we should find a good way to mix L1 and L2 constructs together.
