### ISSUE TITLE
Set default cpu value from 512 to 1024

### ISSUE THREAD

**Issue by gotodeploy** [gotodeploy/cdk-valheim#8]
# Summary

.5 cpu is not enough. Below are metrics of my test server.

## 512 cpu

![metrics-512](https://user-images.githubusercontent.com/1491134/107953780-edebab80-6fde-11eb-82df-ec8688dce92e.png)

## 1024 cpu

![metrics-1024](https://user-images.githubusercontent.com/1491134/107953788-f348f600-6fde-11eb-96cf-0b01b802bbb7.png)

**Comment by guan840912** [comment]
okay, Let's setting CPU 1 core to default.
1 core -  Available memory values: 2048 (2 GB), 3072 (3 GB), 4096 (4 GB), 5120 (5 GB), 6144 (6 GB), 7168 (7 GB), 8192 (8 GB)
