### ISSUE TITLE
Add a parameter for custom log group

### ISSUE THREAD

**Issue by gotodeploy** [gotodeploy/cdk-valheim#9]
Log groups should be handled by users.

**Comment by guan840912** [comment]
Hi @gotodeploy,  are you talking about `logRetention` and `loggroupName` ??

**Comment by gotodeploy** [comment]
> Hi @gotodeploy, are you talking about `logRetention` and `loggroupName` ??

@guan840912 I suppose we can add logGroup as an attribute of ValheimWorldProps like below:

```ts
export interface ValheimWorldProps {
...
  readonly logGroup?: logs.LogGroup;
...
}
```

It is because we don't want to care about future updates on construct props of LogGroup.

**Comment by guan840912** [comment]
cool, make sense
